plans:
  directory: "etc/workout-plan/plans"
  exercise-definition: "etc/workout-plan/exercise-definitions.yml"

database:
  host: "localhost"
  port: "27017"
  user: "mongoadmin"
  password: "secret"
  database: "admin"
  request-timeout: "5"

server:
  ip: "0.0.0.0"
  port: "8080"
  timeout:
    write: "60"
    read: "360"
    idle: "60"
