plans:
  directory: "etc/workout-plan/plans"
  exercise-definition: "etc/workout-plan/exercise-definitions.yml"

database:
  host: "localhost"
  port: "27017"
  user: "mongoadmin"
  password: "secret"
  database: "admin"
  timeout:
    startup: 20
    request: 10

server:
  ip: "0.0.0.0"
  port: "8080"
  timeout:
    write: 60
    read: 360
    idle: 60
