version: '3.7'

services:
  mongodb:
    image: "mongo:4.0"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_INITDB_ROOT_PASSWORD: "secret"

  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./config.yml:/usr/local/bin/config.yml"
      - "./etc/workout-plan/:/etc/workout-plan"
