version: '3.7'

services:
  mongodb:
    image: "mongo:4.0"
    networks:
      - workout-plan
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_INITDB_ROOT_PASSWORD: "secret"

  planserver:
    build: .
    ports:
      - "8080:8080"
    networks:
      - workout-plan
      - wf-frontend
    volumes:
      - "./etc/config.yml:/usr/local/bin/config.yml"
      - "./etc/workout-plan/:/etc/workout-plan"

networks:
  workout-plan:
  wf-frontend:
    external:
      name: wf-frontend